// example/react-press/src/components/SrcLink.tsx
import React from "react"
import { lastRightPart } from "@servicestack/client"

type SrcLink = {
    href:string
    iconSrc?:string
    children?: React.ReactNode
}
export default ({ href, iconSrc, children } : SrcLink) => {
    const fileName = lastRightPart(href, '/')
    return iconSrc 
        ? (<a href={href} className="mr-3 text-gray-500 hover:text-gray-600 text-decoration-none">
            <img src={iconSrc} className="w-5 h-5 inline-flex text-purple-800 mr-1" alt="file icon"/>{fileName}</a>)
        : (<a href={href} className="mr-3 text-gray-400 hover:text-gray-500 text-decoration-none">
            {children} {fileName}</a>)
}

// example/vue-press/src/components/SrcLink.vue
<template>
<a v-if="iconSrc" :href="absoluteHref" class="mr-3 text-gray-500 hover:text-gray-600 text-decoration-none">
  <img :src="iconSrc" class="w-5 h-5 inline-flex text-purple-800 mr-1" alt="file icon">{{ fileName }}</a>
<a v-else :href="absoluteHref" class="mr-3 text-gray-400 hover:text-gray-500 text-decoration-none">
    <slot></slot> {{ fileName }}</a>
</template>

<script setup lang="ts">
import { computed } from "vue"
import { lastRightPart, combinePaths } from "@servicestack/client"

const baseUrl = "https://github.com/ServiceStack/vite-plugin-press/blob/main"

const props = defineProps<{
  href: string
  iconSrc?: string
}>()

const fileName = lastRightPart(props.href, '/')
const absoluteHref = computed(() => props.href.includes('://') ? props.href : combinePaths(baseUrl, props.href))
</script>
